name: Run Docker Command

on:
  workflow_call:
    inputs:
      image:
        description: "Docker image to run"
        required: true
        type: string
      command:
        description: "Command to execute in container"
        required: true
        type: string

jobs:
  run-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Run container command
        run: docker run --rm -v "${{ github.workspace }}:/workspace" ${{ inputs.image }} ${{ inputs.command }}
