name: Build and Push Docker Image

on:
  workflow_dispatch:

permissions:
  packages: write
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Setup steps
        uses: ./.github/actions/setup-steps
        with:
          GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
          actor: ${{ github.actor }}

      - name: Build and push python only image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          build-args: SELECT=production_no_tex
          tags: ghcr.io/${{ github.repository_owner }}/cv_builder:latest

      - name: Build and push tex-abled image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          build-args: SELECT=production_tex
          tags: ghcr.io/${{ github.repository_owner }}/cv_builder_tex:latest
